CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE administrator (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_phc TEXT NOT NULL,
    password_version BIGINT NOT NULL DEFAULT 1 CHECK (password_version > 0),
    password_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0)
);

CREATE UNIQUE INDEX administrator_singleton_idx ON administrator ((true));

CREATE TABLE admin_session (
    id UUID PRIMARY KEY,
    administrator_id UUID NOT NULL REFERENCES administrator(id) ON DELETE CASCADE,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    csrf_digest BYTEA NOT NULL CHECK (octet_length(csrf_digest) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    idle_expires_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CHECK (last_activity_at >= created_at),
    CHECK (idle_expires_at > created_at),
    CHECK (absolute_expires_at > created_at),
    CHECK (idle_expires_at <= absolute_expires_at)
);

CREATE TABLE login_attempt (
    id UUID PRIMARY KEY,
    administrator_id UUID REFERENCES administrator(id) ON DELETE SET NULL,
    account_bucket TEXT NOT NULL,
    entry_bucket TEXT NOT NULL,
    source_bucket TEXT NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    succeeded BOOLEAN NOT NULL,
    failure_reason TEXT,
    CHECK (failure_reason IS NULL OR failure_reason <> '')
);

CREATE TABLE login_rate_limit (
    bucket_key TEXT PRIMARY KEY,
    failure_count INTEGER NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
    window_started_at TIMESTAMPTZ NOT NULL,
    cooldown_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE login_rate_limit_reservation (
    id UUID PRIMARY KEY,
    bucket_key TEXT NOT NULL REFERENCES login_rate_limit(bucket_key) ON DELETE RESTRICT,
    leased_until TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX login_rate_limit_reservation_bucket_idx
    ON login_rate_limit_reservation (bucket_key, leased_until);

CREATE TABLE system_setting (
    id UUID PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0)
);

CREATE TABLE download_rule (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT true,
    match_action TEXT NOT NULL CHECK (match_action IN ('download', 'metadata_only', 'ignore')),
    default_action TEXT NOT NULL CHECK (default_action IN ('download', 'metadata_only', 'ignore')),
    current_version_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    sort_order BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
);

CREATE INDEX download_rule_sort_order_idx ON download_rule (sort_order, id);

CREATE TABLE rule_version (
    id UUID PRIMARY KEY,
    rule_id UUID NOT NULL REFERENCES download_rule(id) ON DELETE CASCADE,
    version BIGINT NOT NULL CHECK (version > 0),
    base_version BIGINT CHECK (base_version IS NULL OR base_version > 0),
    schema_version BIGINT NOT NULL CHECK (schema_version > 0),
    definition JSONB NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES administrator(id) ON DELETE SET NULL,
    UNIQUE (rule_id, id),
    UNIQUE (rule_id, version),
    CHECK (base_version IS NULL OR base_version < version)
);

ALTER TABLE download_rule
    ADD CONSTRAINT download_rule_current_version_id_fkey
    FOREIGN KEY (id, current_version_id)
    REFERENCES rule_version(rule_id, id)
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

CREATE FUNCTION reject_rule_version_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- A published version may disappear only as part of deleting its parent rule.
    IF TG_OP = 'DELETE'
       AND NOT EXISTS (SELECT 1 FROM download_rule WHERE id = OLD.rule_id) THEN
        RETURN OLD;
    END IF;

    RAISE EXCEPTION 'published rule versions are immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER rule_version_immutable
BEFORE UPDATE OR DELETE ON rule_version
FOR EACH ROW
EXECUTE FUNCTION reject_rule_version_mutation();

CREATE TABLE rule_draft (
    id UUID PRIMARY KEY,
    rule_id UUID NOT NULL REFERENCES download_rule(id) ON DELETE CASCADE,
    base_version BIGINT,
    schema_version BIGINT NOT NULL CHECK (schema_version > 0),
    definition JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    UNIQUE (rule_id)
);

CREATE TABLE pixiv_account (
    id UUID PRIMARY KEY,
    pixiv_user_id BIGINT NOT NULL UNIQUE CHECK (pixiv_user_id > 0),
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    state TEXT NOT NULL CONSTRAINT pixiv_account_state_check
        CHECK (state IN ('unconfigured', 'validating', 'normal', 'restricted', 'credential_invalid')),
    cookie_key_id TEXT,
    cookie_nonce BYTEA CHECK (octet_length(cookie_nonce) >= 12),
    cookie_ciphertext BYTEA CHECK (octet_length(cookie_ciphertext) > 0),
    last_validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    user_agent TEXT NOT NULL DEFAULT 'PixivArchive/0.1',
    bookmark_writeback_enabled BOOLEAN NOT NULL DEFAULT false,
    is_current BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT pixiv_account_credential_state_check CHECK (
        (
            state = 'unconfigured'
            AND cookie_key_id IS NULL
            AND cookie_nonce IS NULL
            AND cookie_ciphertext IS NULL
        )
        OR (
            state <> 'unconfigured'
            AND cookie_key_id IS NOT NULL
            AND cookie_nonce IS NOT NULL
            AND cookie_ciphertext IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX pixiv_account_one_current_idx
    ON pixiv_account (is_current)
    WHERE is_current = true;

CREATE TABLE job (
    id UUID PRIMARY KEY,
    priority_class TEXT NOT NULL CHECK (priority_class IN (
        'immediate',
        'manual_import',
        'scheduled_collection',
        'background_maintenance'
    )),
    kind TEXT NOT NULL CONSTRAINT job_kind_check CHECK (kind IN (
        'scheduled_collection',
        'ranking_collection',
        'following_collection',
        'bookmarks_collection',
        'import_artist',
        'import_work',
        'download_media',
        'generate_derivative',
        'purge_trash'
    )),
    payload JSONB NOT NULL,
    state TEXT NOT NULL CONSTRAINT job_state_check CHECK (state IN (
        'queued',
        'running',
        'waiting_account',
        'waiting_storage',
        'completed',
        'failed',
        'cancelled'
    )),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_owner UUID,
    lease_expires_at TIMESTAMPTZ,
    error_class TEXT,
    retryable BOOLEAN,
    next_retry_at TIMESTAMPTZ,
    resource_revision BIGINT NOT NULL DEFAULT 1 CHECK (resource_revision > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    pixiv_account_id UUID REFERENCES pixiv_account(id) ON DELETE SET NULL,
    retryable_failure_count INTEGER NOT NULL DEFAULT 0 CHECK (retryable_failure_count >= 0),
    CONSTRAINT job_running_lease_check
        CHECK ((state = 'running') = (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT job_retry_time_check CHECK (next_retry_at IS NULL OR state = 'failed'),
    CONSTRAINT job_waiting_account_check CHECK (
        state <> 'waiting_account'
        OR (
            pixiv_account_id IS NOT NULL
            AND lease_owner IS NULL
            AND lease_expires_at IS NULL
            AND next_retry_at IS NULL
        )
    ),
    CONSTRAINT job_waiting_storage_check CHECK (
        state <> 'waiting_storage'
        OR (
            kind IN ('download_media', 'generate_derivative')
            AND lease_owner IS NULL
            AND lease_expires_at IS NULL
            AND next_retry_at IS NULL
        )
    )
);

CREATE INDEX job_claim_runnable_idx
    ON job (priority_class, available_at, next_retry_at, created_at)
    WHERE state IN ('queued', 'failed', 'running');

CREATE INDEX job_waiting_account_idx
    ON job (pixiv_account_id, updated_at)
    WHERE state = 'waiting_account';

CREATE INDEX job_waiting_storage_idx
    ON job (updated_at)
    WHERE state = 'waiting_storage';

CREATE UNIQUE INDEX job_one_active_trash_purge_idx
    ON job ((payload ->> 'work_id'))
    WHERE kind = 'purge_trash'
      AND (
          state IN ('queued', 'running', 'waiting_account')
          OR (state = 'failed' AND retryable = true)
      );

CREATE TABLE job_attempt (
    id UUID PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES job(id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    state TEXT NOT NULL CONSTRAINT job_attempt_state_check CHECK (state IN (
        'running',
        'waiting_storage',
        'completed',
        'failed',
        'cancelled'
    )),
    error_class TEXT,
    retryable BOOLEAN,
    message TEXT,
    trace_id UUID,
    UNIQUE (job_id, attempt_number),
    CHECK (finished_at IS NULL OR finished_at >= started_at),
    CHECK ((state = 'running') = (finished_at IS NULL))
);

CREATE UNIQUE INDEX job_attempt_one_running_idx
    ON job_attempt (job_id)
    WHERE state = 'running';

CREATE TABLE app_event (
    id BIGSERIAL PRIMARY KEY,
    resource TEXT NOT NULL CONSTRAINT app_event_resource_check CHECK (resource IN (
        'job',
        'rule',
        'work',
        'pixiv_bookmark',
        'deletion_marker',
        'subscription',
        'pixiv_account',
        'system_setting',
        'administrator'
    )),
    resource_id UUID NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX app_event_replay_idx ON app_event (id);
CREATE INDEX app_event_resource_idx ON app_event (resource, resource_id, id);

CREATE TABLE subscription (
    id UUID PRIMARY KEY,
    pixiv_account_id UUID NOT NULL REFERENCES pixiv_account(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    kind TEXT NOT NULL CONSTRAINT subscription_kind_check
        CHECK (kind IN ('ranking', 'following', 'bookmarks')),
    enabled BOOLEAN NOT NULL DEFAULT true,
    schedule JSONB NOT NULL,
    params JSONB NOT NULL,
    last_run_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    pending_run BOOLEAN NOT NULL DEFAULT false,
    recent_state TEXT NOT NULL DEFAULT 'never_run'
        CHECK (recent_state IN ('never_run', 'running', 'succeeded', 'failed', 'paused')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    rule_id UUID REFERENCES download_rule(id) ON DELETE SET NULL,
    pending_cursor_kind TEXT NOT NULL DEFAULT 'normal'
        CHECK (pending_cursor_kind IN ('normal', 'backfill'))
);

CREATE UNIQUE INDEX subscription_following_account_unique_idx
    ON subscription (pixiv_account_id)
    WHERE kind = 'following';

CREATE UNIQUE INDEX subscription_bookmarks_account_unique_idx
    ON subscription (pixiv_account_id)
    WHERE kind = 'bookmarks';

CREATE TABLE pixiv_following_author (
    pixiv_account_id UUID NOT NULL REFERENCES pixiv_account(id) ON DELETE CASCADE,
    pixiv_artist_id BIGINT NOT NULL CHECK (pixiv_artist_id > 0),
    display_name TEXT NOT NULL CHECK (length(btrim(display_name)) > 0),
    avatar_url TEXT,
    visibility TEXT NOT NULL CHECK (visibility IN ('public', 'private')),
    refreshed_at TIMESTAMPTZ NOT NULL,
    last_collected_at TIMESTAMPTZ,
    PRIMARY KEY (pixiv_account_id, pixiv_artist_id)
);

CREATE TABLE pixiv_following_author_exclusion (
    pixiv_account_id UUID NOT NULL,
    pixiv_artist_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pixiv_account_id, pixiv_artist_id),
    FOREIGN KEY (pixiv_account_id, pixiv_artist_id)
        REFERENCES pixiv_following_author (pixiv_account_id, pixiv_artist_id)
        ON DELETE CASCADE
);

CREATE TABLE subscription_cursor (
    id UUID PRIMARY KEY,
    subscription_id UUID NOT NULL REFERENCES subscription(id) ON DELETE CASCADE,
    cursor_kind TEXT NOT NULL CHECK (cursor_kind IN ('normal', 'backfill')),
    cursor_value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_key TEXT NOT NULL DEFAULT 'default',
    CONSTRAINT subscription_cursor_source_key_check CHECK (length(source_key) > 0),
    CONSTRAINT subscription_cursor_subscription_source_key
        UNIQUE (subscription_id, cursor_kind, source_key)
);

CREATE TABLE subscription_run (
    id UUID PRIMARY KEY,
    subscription_id UUID NOT NULL REFERENCES subscription(id) ON DELETE CASCADE,
    job_id UUID REFERENCES job(id) ON DELETE SET NULL,
    trigger_kind TEXT NOT NULL CHECK (trigger_kind IN ('scheduled', 'manual', 'merged_pending', 'backfill')),
    state TEXT NOT NULL CHECK (state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    discovered_count INTEGER NOT NULL DEFAULT 0 CHECK (discovered_count >= 0),
    ignored_count INTEGER NOT NULL DEFAULT 0 CHECK (ignored_count >= 0),
    error_class TEXT,
    trace_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cursor_kind TEXT NOT NULL DEFAULT 'normal' CHECK (cursor_kind IN ('normal', 'backfill')),
    params_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    rule_version_id UUID REFERENCES rule_version(id) ON DELETE SET NULL,
    rule_document JSONB,
    CONSTRAINT subscription_run_rule_snapshot_check
        CHECK (rule_version_id IS NULL OR rule_document IS NOT NULL),
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE UNIQUE INDEX subscription_run_one_active_per_subscription_idx
    ON subscription_run (subscription_id)
    WHERE state IN ('queued', 'running');

CREATE TABLE subscription_run_unit (
    id UUID PRIMARY KEY,
    subscription_run_id UUID NOT NULL REFERENCES subscription_run(id) ON DELETE CASCADE,
    job_id UUID REFERENCES job(id) ON DELETE SET NULL,
    source_key TEXT NOT NULL CHECK (length(source_key) > 0),
    cursor_kind TEXT NOT NULL CHECK (cursor_kind IN ('normal', 'backfill')),
    params_snapshot JSONB NOT NULL,
    cursor_snapshot JSONB,
    state TEXT NOT NULL CHECK (state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    discovered_count INTEGER NOT NULL DEFAULT 0 CHECK (discovered_count >= 0),
    ignored_count INTEGER NOT NULL DEFAULT 0 CHECK (ignored_count >= 0),
    error_class TEXT,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (subscription_run_id, source_key),
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX subscription_run_unit_job_idx ON subscription_run_unit (job_id);
CREATE INDEX subscription_run_unit_parent_state_idx ON subscription_run_unit (subscription_run_id, state);

CREATE TABLE ranking_entry (
    id UUID PRIMARY KEY,
    subscription_run_id UUID NOT NULL REFERENCES subscription_run(id) ON DELETE CASCADE,
    pixiv_work_id BIGINT NOT NULL CHECK (pixiv_work_id > 0),
    rank INTEGER NOT NULL CHECK (rank > 0),
    score JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    subscription_run_unit_id UUID REFERENCES subscription_run_unit(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL DEFAULT 'legacy',
    CONSTRAINT ranking_entry_source_key_check CHECK (length(source_key) > 0),
    CONSTRAINT ranking_entry_subscription_source_work_key
        UNIQUE (subscription_run_id, source_key, pixiv_work_id)
);

CREATE TABLE import_run (
    id UUID PRIMARY KEY,
    pixiv_account_id UUID NOT NULL REFERENCES pixiv_account(id) ON DELETE CASCADE,
    job_id UUID REFERENCES job(id) ON DELETE SET NULL,
    import_kind TEXT NOT NULL CHECK (import_kind IN ('artist', 'work')),
    target_pixiv_id BIGINT NOT NULL CHECK (target_pixiv_id > 0),
    forced BOOLEAN NOT NULL DEFAULT false,
    rule_version_id UUID REFERENCES rule_version(id) ON DELETE SET NULL,
    status TEXT NOT NULL CONSTRAINT import_run_status_check CHECK (status IN (
        'queued',
        'running',
        'metadata_saved',
        'download_queued',
        'ignored',
        'blocked_by_deletion_marker',
        'failed',
        'cancelled'
    )),
    discovered_count INTEGER NOT NULL DEFAULT 0 CHECK (discovered_count >= 0),
    saved_count INTEGER NOT NULL DEFAULT 0 CHECK (saved_count >= 0),
    error_class TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    params JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT
);

CREATE TABLE import_candidate (
    id UUID PRIMARY KEY,
    import_run_id UUID NOT NULL REFERENCES import_run(id) ON DELETE CASCADE,
    pixiv_work_id BIGINT NOT NULL CHECK (pixiv_work_id > 0),
    action TEXT NOT NULL CHECK (action IN ('download', 'metadata_only', 'ignore', 'blocked')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (import_run_id, pixiv_work_id)
);

CREATE TABLE bookmark_writeback_command (
    id UUID PRIMARY KEY,
    pixiv_account_id UUID NOT NULL REFERENCES pixiv_account(id) ON DELETE CASCADE,
    operation TEXT NOT NULL CHECK (operation IN ('add', 'remove')),
    target_pixiv_id BIGINT NOT NULL CHECK (target_pixiv_id > 0),
    status TEXT NOT NULL CHECK (status IN ('disabled', 'succeeded', 'failed')),
    error_class TEXT,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE artist (
    id UUID PRIMARY KEY,
    pixiv_artist_id BIGINT NOT NULL UNIQUE CHECK (pixiv_artist_id > 0),
    name TEXT NOT NULL,
    account_name TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0)
);

CREATE TABLE tag (
    id UUID PRIMARY KEY,
    raw_name TEXT NOT NULL,
    translated_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX tag_normalized_name_idx ON tag (lower(btrim(raw_name)));

CREATE TABLE series (
    id UUID PRIMARY KEY,
    pixiv_series_id BIGINT NOT NULL UNIQUE CHECK (pixiv_series_id IS NULL OR pixiv_series_id > 0),
    title TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE work (
    id UUID PRIMARY KEY,
    pixiv_work_id BIGINT NOT NULL UNIQUE CHECK (pixiv_work_id > 0),
    artist_id UUID NOT NULL REFERENCES artist(id) ON DELETE RESTRICT,
    series_id UUID REFERENCES series(id) ON DELETE SET NULL,
    current_revision_id UUID,
    collection_state TEXT NOT NULL CHECK (collection_state IN ('collected', 'metadata_only', 'trash')),
    source_state TEXT NOT NULL CHECK (source_state IN ('present', 'missing', 'deleted', 'restricted')),
    bookmark_count BIGINT CHECK (bookmark_count IS NULL OR bookmark_count >= 0),
    view_count BIGINT CHECK (view_count IS NULL OR view_count >= 0),
    like_count BIGINT CHECK (like_count IS NULL OR like_count >= 0),
    comment_count BIGINT CHECK (comment_count IS NULL OR comment_count >= 0),
    quick_viewed_at TIMESTAMPTZ,
    last_collected_at TIMESTAMPTZ,
    trashed_at TIMESTAMPTZ,
    resource_revision BIGINT NOT NULL DEFAULT 1 CHECK (resource_revision > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE work_revision (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    caption TEXT,
    work_kind TEXT NOT NULL CHECK (work_kind IN ('illustration', 'manga', 'ugoira')),
    page_count INTEGER NOT NULL CHECK (page_count > 0),
    width INTEGER CHECK (width IS NULL OR width > 0),
    height INTEGER CHECK (height IS NULL OR height > 0),
    sanity_level TEXT NOT NULL CHECK (sanity_level IN ('all_age', 'r18', 'r18g', 'unknown')),
    pixiv_created_at TIMESTAMPTZ,
    pixiv_updated_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    search_document TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A')
        || setweight(to_tsvector('simple', coalesce(caption, '')), 'D')
    ) STORED,
    UNIQUE (work_id, id)
);

ALTER TABLE work
    ADD CONSTRAINT work_current_revision_id_fkey
    FOREIGN KEY (id, current_revision_id)
    REFERENCES work_revision(work_id, id)
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE work_tag (
    work_id UUID NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    tag_id UUID NOT NULL REFERENCES tag(id) ON DELETE RESTRICT,
    PRIMARY KEY (work_id, tag_id)
);

CREATE TABLE work_page (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    page_index INTEGER NOT NULL CHECK (page_index >= 0),
    current_media_revision_id UUID,
    source_url TEXT,
    source_path TEXT,
    width INTEGER CHECK (width IS NULL OR width > 0),
    height INTEGER CHECK (height IS NULL OR height > 0),
    source_state TEXT NOT NULL DEFAULT 'present' CHECK (source_state IN ('present', 'deleted')),
    UNIQUE (work_id, page_index)
);

CREATE TABLE media_revision (
    id UUID PRIMARY KEY,
    work_page_id UUID NOT NULL REFERENCES work_page(id) ON DELETE CASCADE,
    revision_number BIGINT NOT NULL CHECK (revision_number > 0),
    media_kind TEXT NOT NULL CHECK (media_kind IN ('source_image', 'ugoira_zip')),
    format TEXT NOT NULL CHECK (format IN ('jpg', 'jpeg', 'png', 'gif', 'zip')),
    source_path TEXT NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    sha256 BYTEA NOT NULL CHECK (octet_length(sha256) = 32),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (work_page_id, id),
    UNIQUE (work_page_id, revision_number)
);

ALTER TABLE work_page
    ADD CONSTRAINT work_page_current_media_revision_id_fkey
    FOREIGN KEY (id, current_media_revision_id)
    REFERENCES media_revision(work_page_id, id)
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE derivative (
    id UUID PRIMARY KEY,
    media_revision_id UUID NOT NULL REFERENCES media_revision(id) ON DELETE CASCADE,
    derivative_kind TEXT NOT NULL CHECK (derivative_kind IN ('waterfall_thumbnail', 'ugoira_cover')),
    format TEXT NOT NULL CHECK (format IN ('webp', 'avif')),
    path TEXT NOT NULL,
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    dominant_color TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (media_revision_id, derivative_kind, format)
);

CREATE TABLE overview_decoration_selection (
    selection_date DATE NOT NULL,
    position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 2),
    work_id UUID REFERENCES work(id) ON DELETE SET NULL,
    PRIMARY KEY (selection_date, position)
);

CREATE TABLE trash_entry (
    work_id UUID PRIMARY KEY REFERENCES work(id) ON DELETE CASCADE,
    previous_collection_state TEXT NOT NULL CHECK (previous_collection_state IN ('collected', 'metadata_only')),
    trashed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    scheduled_purge_at TIMESTAMPTZ NOT NULL,
    purge_state TEXT NOT NULL CHECK (purge_state IN ('pending', 'running', 'failed')),
    failure_message TEXT,
    purge_attempts INTEGER NOT NULL DEFAULT 0 CHECK (purge_attempts >= 0),
    last_attempt_at TIMESTAMPTZ,
    failure_details JSONB NOT NULL DEFAULT '[]'::jsonb,
    CHECK (scheduled_purge_at >= trashed_at)
);

CREATE TABLE deletion_marker (
    id UUID PRIMARY KEY,
    pixiv_work_id BIGINT NOT NULL UNIQUE CHECK (pixiv_work_id > 0),
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deletion_method TEXT NOT NULL CHECK (deletion_method IN ('manual_purge', 'retention_expired'))
);

CREATE TABLE pixiv_work_bookmark (
    pixiv_account_id UUID NOT NULL REFERENCES pixiv_account(id) ON DELETE CASCADE,
    work_id UUID NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    pixiv_bookmark_id BIGINT CHECK (pixiv_bookmark_id IS NULL OR pixiv_bookmark_id > 0),
    visibility TEXT NOT NULL CHECK (visibility IN ('public', 'private')),
    active BOOLEAN NOT NULL DEFAULT true,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pixiv_account_id, work_id)
);

CREATE UNIQUE INDEX pixiv_work_bookmark_remote_id_unique_idx
    ON pixiv_work_bookmark (pixiv_account_id, pixiv_bookmark_id)
    WHERE pixiv_bookmark_id IS NOT NULL;

CREATE INDEX pixiv_work_bookmark_active_work_idx
    ON pixiv_work_bookmark (work_id)
    WHERE active = true;

CREATE TABLE pixiv_bookmark_sync_state (
    pixiv_account_id UUID PRIMARY KEY REFERENCES pixiv_account(id) ON DELETE CASCADE,
    last_full_reconciled_at TIMESTAMPTZ,
    resource_revision BIGINT NOT NULL DEFAULT 0 CHECK (resource_revision >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE worker_heartbeat (
    singleton BOOLEAN PRIMARY KEY DEFAULT true CHECK (singleton),
    worker_id UUID NOT NULL,
    version TEXT NOT NULL CHECK (btrim(version) <> ''),
    git_commit TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    CHECK (last_seen_at >= started_at)
);

CREATE TABLE media_artifact_intent (
    id UUID PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES job(id) ON DELETE RESTRICT,
    relative_path TEXT NOT NULL UNIQUE CHECK (length(relative_path) > 0),
    cleanup_attempts INTEGER NOT NULL DEFAULT 0 CHECK (cleanup_attempts >= 0),
    cleanup_error TEXT,
    last_cleanup_at TIMESTAMPTZ,
    cleanup_after TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX media_artifact_intent_job_idx
    ON media_artifact_intent (job_id, created_at);

CREATE INDEX artist_name_trgm_idx ON artist USING gin (name gin_trgm_ops);
CREATE INDEX tag_raw_name_trgm_idx ON tag USING gin (raw_name gin_trgm_ops);
CREATE INDEX tag_translated_name_trgm_idx ON tag USING gin (translated_name gin_trgm_ops);
CREATE INDEX series_title_trgm_idx ON series USING gin (title gin_trgm_ops);
CREATE INDEX work_state_updated_idx ON work (collection_state, updated_at DESC);
CREATE INDEX work_revision_title_trgm_idx ON work_revision USING gin (title gin_trgm_ops);
CREATE INDEX work_revision_search_document_idx ON work_revision USING gin (search_document);
CREATE INDEX deletion_marker_pixiv_work_id_idx ON deletion_marker (pixiv_work_id);
CREATE INDEX media_revision_sha256_idx ON media_revision (sha256);

CREATE INDEX work_page_present_idx
    ON work_page (work_id, page_index)
    WHERE source_state = 'present';

CREATE INDEX trash_entry_due_idx
    ON trash_entry (scheduled_purge_at, work_id)
    WHERE purge_state IN ('pending', 'failed');

CREATE INDEX work_collected_artist_directory_idx
    ON work (artist_id, last_collected_at DESC NULLS LAST, updated_at DESC, id DESC)
    WHERE collection_state = 'collected';

CREATE INDEX work_collected_series_directory_idx
    ON work (series_id, last_collected_at DESC NULLS LAST, updated_at DESC, id DESC)
    WHERE collection_state = 'collected' AND series_id IS NOT NULL;

CREATE INDEX work_tag_tag_work_idx ON work_tag (tag_id, work_id);

CREATE INDEX work_collected_recent_idx
    ON work (last_collected_at DESC NULLS LAST, updated_at DESC, id DESC)
    WHERE collection_state = 'collected';

CREATE INDEX trash_entry_list_idx ON trash_entry (scheduled_purge_at, work_id);
CREATE INDEX trash_entry_state_list_idx ON trash_entry (purge_state, scheduled_purge_at, work_id);
